# Generated by Django 4.2.3 on 2023-10-08 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('Reason', models.CharField(max_length=100, verbose_name='신고 사유')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_target', to=settings.AUTH_USER_MODEL, verbose_name='신고 대상')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '신고 관리',
                'verbose_name_plural': '신고 관리',
            },
        ),
    ]
