# Generated by Django 4.2.3 on 2023-10-01 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relate', to=settings.AUTH_USER_MODEL, verbose_name='관계자')),
                ('relation2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relate2', to=settings.AUTH_USER_MODEL, verbose_name='관계자2')),
            ],
            options={
                'verbose_name': '채팅방 관리',
                'verbose_name_plural': '채팅방 관리',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('message', models.TextField(default='', verbose_name='메시지')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('type', models.IntegerField(default=1, verbose_name='메세지 타입')),
                ('args', models.TextField(blank=True, default=None, null=True, verbose_name='인자값')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_receiver', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_room', to='chat.room', verbose_name='채팅방')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_sender', to=settings.AUTH_USER_MODEL, verbose_name='전송자')),
            ],
            options={
                'verbose_name': '메시지 관리',
                'verbose_name_plural': '메시지 관리',
            },
        ),
    ]
