# Generated by Django 4.2.3 on 2023-11-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_tagset_room_tagset2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='room',
            name='latest_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_message', to='chat.message', verbose_name='가장 최근 메시지'),
        ),
    ]
