# Generated by Django 4.2.3 on 2023-10-01 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('place', models.CharField(max_length=12, verbose_name='장소')),
                ('person', models.CharField(max_length=12, verbose_name='대상')),
                ('method', models.CharField(max_length=12, verbose_name='행동')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagset_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '태그셋 관리',
                'verbose_name_plural': '태그셋 관리',
            },
        ),
    ]
