# Generated by Django 4.2.3 on 2023-10-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tagset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='place',
            field=models.CharField(choices=[('북악관', '북악관'), ('북악관', '북악관'), ('북악관', '북악관'), ('북악관', '북악관')], max_length=12, verbose_name='장소'),
        ),
    ]
