# Generated by Django 4.2.3 on 2023-10-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='significant',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='accounts.significant', verbose_name='특이사항'),
        ),
    ]
