# Generated by Django 4.2.3 on 2023-10-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.IntegerField(null=True),
        ),
    ]
