# Generated by Django 4.2.3 on 2023-11-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('1학년', '1학년'), ('2학년', '2학년'), ('3학년', '3학년'), ('4학년', '4학년'), ('5학년', '5학년'), ('졸업생', '졸업생'), ('기타', '기타')], default='', max_length=10, null=True, verbose_name='학년'),
        ),
    ]
