# Generated by Django 4.2.3 on 2023-11-05 07:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='이름')),
                ('profile', models.ImageField(upload_to='', verbose_name='프로필 이미지')),
            ],
            options={
                'verbose_name': '프로필 이미지 프리셋',
                'verbose_name_plural': '프로필 이미지 프리셋',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(choices=[('글로벌인문지역대학', '글로벌인문지역대학'), ('사회과학대학', '사회과학대학'), ('법과대학', '법과대학'), ('경상대학', '경상대학'), ('경영대학', '경영대학'), ('창의공과대학', '창의공과대학'), ('소프트웨어융합대학', '소프트웨어융합대학'), ('자동차융합대학', '자동차융합대학'), ('과학기술대학', '과학기술대학'), ('건축대학', '건축대학'), ('조형대학', '조형대학'), ('예술대학', '예술대학'), ('체육대학', '체육대학'), ('미래모빌리티학과', '미래모빌리티학과'), ('교양대학', '교양대학'), ('인문기술융합학부', '인문기술융합학부')], default='', max_length=20, verbose_name='단과대학'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_profile', to='accounts.profile'),
        ),
    ]
