# Generated by Django 4.2.3 on 2023-10-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='이름'),
        ),
    ]
