# Generated by Django 4.2.3 on 2023-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagset',
            name='introduction',
            field=models.CharField(max_length=30, null=True, verbose_name='한줄소개'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='method',
            field=models.CharField(choices=[('스터디', '스터디'), ('모각코', '모각코'), ('식사', '식사'), ('수다', '수다')], max_length=12, verbose_name='행동'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='person',
            field=models.CharField(choices=[('유학생', '유학생'), ('타과생', '타과생'), ('선배', '선배'), ('후배', '후배'), ('23학번', '23학번'), ('22학번', '22학번'), ('새내기', '새내기'), ('아무랑', '아무랑'), ('동기', '동기')], max_length=12, verbose_name='대상'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='place',
            field=models.CharField(choices=[('북악관', '북악관'), ('예술대', '예술대'), ('미래관', '미래관'), ('공학관', '공학관'), ('경상관', '경상관'), ('본부관', '본부관'), ('용두리', '용두리'), ('도서관', '도서관'), ('복지관 열람실', '복지관 열람실'), ('자율주행스튜디오', '자율주행스튜디오'), ('어디서든', '어디서든')], max_length=12, verbose_name='장소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True, verbose_name='평점'),
        ),
    ]
