# Generated by Django 4.2.3 on 2023-10-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_tagset_introduction_alter_tagset_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagset',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='significant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_number',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='method',
            field=models.CharField(max_length=12, verbose_name='행동'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='person',
            field=models.CharField(max_length=12, verbose_name='대상'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='place',
            field=models.CharField(choices=[('북악관', '북악관'), ('북악관', '북악관'), ('북악관', '북악관'), ('북악관', '북악관')], max_length=12, verbose_name='장소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='이름'),
        ),
    ]
