# Generated by Django 4.2.3 on 2023-10-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_user_birthday_remove_user_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='tagset',
            name='isSameDepartment',
            field=models.BooleanField(default=True, verbose_name='과 동일'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='method',
            field=models.CharField(choices=[('공부', '공부'), ('식사', '식사'), ('수다', '수다'), ('카페', '카페'), ('산책', '산책'), ('운동', '운동'), ('친구', '친구')], max_length=12, verbose_name='행동'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='person',
            field=models.CharField(choices=[], max_length=12, verbose_name='대상'),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='place',
            field=models.CharField(choices=[('북악관', '북악관'), ('예술관', '예술관'), ('복지관', '복지관'), ('공학관', '공학관'), ('법학관', '법학관'), ('대운동장', '대운동장'), ('도서관', '도서관'), ('교내 생활관', '교내 생활관'), ('웰니스', '웰니스'), ('빵집', '빵집'), ('교내 카페', '교내 카페'), ('학생식당', '학생식당'), ('아무데나', '아무데나')], max_length=12, verbose_name='장소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.IntegerField(null=True),
        ),
    ]
