# Generated by Django 4.2.3 on 2023-10-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_grade_user_gender_alter_user_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='significant',
            field=models.JSONField(blank=True, null=True, verbose_name='특이사항'),
        ),
    ]
